### ISSUE TITLE
OAuth Error

### ISSUE THREAD

**Issue by APP4RK** [Yakitrak/ticktick-alfred-workflow#1]
Receive the following error when tsetup1 is entered in Alfred:

OAuth Error
error="invalid_request", error_description="At least one redirect_uri must be registered with the client."

Client ID and Client Secret are set as per your guide. 

As a result, there is no option to copy the code to tsetup2. 

Mac OS - 14.2.1
Alfred - 5.1.4 

<img width="705" alt="Screenshot 2024-01-05 at 21 14 17" src="https://github.com/Yakitrak/ticktick-alfred-workflow/assets/155759988/5a31eda6-0f9e-469b-8bcc-23af1466bb51">

Tried changing ID and Secret and re-installing workflow, but still receive the same response.

Hope you can help.

**Comment by ibrahimkettaneh** [comment]
I was getting a similar error with ticktask.

This should be fixable fbecause I was having the exact same error and was able to get it working with ticktask.

I think a big part of the solution had been adding that the oauth redirect url is http://127.0.0.1:8080, taking into account whichever port this may be at for you,  it is for you in the ticktick developer area.

I hope this helps. :grin:

**Comment by avichou** [comment]
> I was getting a similar error with ticktask.
> 
> This should be fixable fbecause I was having the exact same error and was able to get it working with ticktask.
> 
> I think a big part of the solution had been adding that the oauth redirect url is http://127.0.0.1:8080, taking into account whichever port this may be at for you, it is for you in the ticktick developer area.
> 
> I hope this helps. 😁

how do you figure which port it is for you pls ?

**Comment by Yakitrak** [comment]
Hi sorry for the late reply, it seems TickTick changed their process slightly and the docs were out of date - I've now updated the [Setup](https://github.com/Yakitrak/ticktick-alfred-workflow?tab=readme-ov-file#setup) stage in the README. Please try again and let me know if you have any other issues.

**Comment by avichou** [comment]
still having the issue . workflow wasn't working anymore for me so i tried recreating new credentials and "app", but now it won't let me 

OAuth Error
error="invalid_request", error_description="At least one redirect_uri must be registered with the client."
