### ISSUE TITLE
Can't get all tasks from TickTick

### ISSUE THREAD

**Issue by johnnyitd** [Yakitrak/ticktick-alfred-workflow#2]
Hi!
I wanted to use the workflow, but it is not able to fetch all my tasks. I got more than 1000 tasks, most of them still not done in TickTick. 

In debug I get error 443 from TickTick API. It downloads many tasks, but doesn't get to current days. I believe this might be due to the API limit on their side. 

Can you please add filters to the workflow?
- Do not get overdue tasks
- Do not get tasks before certain date

Really want to use it, but can't for now. Thanks!

**Comment by Yakitrak** [comment]
Thank you for the feedback and apologies for the late response! Unfortunately as you said this is a API limitation, I have to get all the lists and then get all tasks from each list. There isn't a way to filter or compare dates until after I have retrieved all responses.
